In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.11085192, 0.07365606, 0.56197868, 0.50556367, 0.22379433])

In [22]:
np.random.rand(5,4)

array([[0.55287763, 0.48312241, 0.82802204, 0.81108404],
       [0.56939758, 0.66224373, 0.91577875, 0.37369793],
       [0.79684009, 0.14123977, 0.41033047, 0.42201392],
       [0.28818962, 0.61012454, 0.79157012, 0.55608863],
       [0.38691316, 0.74886875, 0.28737851, 0.13218178]])

In [26]:
np.random.randn(2,3)

array([[ 0.3404574 ,  0.52989568,  0.62675139],
       [ 0.46369938, -0.78715944, -0.81476005]])

In [28]:
np.random.randint(1,100,10)

array([90, 60, 45, 93, 16, 74, 33,  8, 86, 39])

In [29]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)
ranarr

array([19,  1,  4, 13, 26, 37,  9, 46,  5, 12])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()


46

In [38]:
ranarr.min()

1

In [39]:
ranarr.argmax()

7

In [41]:
arr.shape


(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

2

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8]

8

In [50]:
arr[1:5]

array([1, 2, 3, 4])

In [51]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [52]:
arr[:5]

array([0, 1, 2, 3, 4])

In [53]:
arr[0:5] = 100

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [57]:
slice_of_arr[:] = 99

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy = arr.copy()

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_copy[:] =100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[0][0]

5

In [66]:
#grab everything till row 2 and grab from onwards column till end
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [68]:
arr_2d[1,:]

array([20, 25, 30])

In [69]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [70]:
arr = np.arange(1,11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
bool_arr = arr > 5 
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [75]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [78]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [84]:
arr = np.arange(0,11)

In [85]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [86]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [89]:
1/0


ZeroDivisionError: division by zero

In [90]:
arr / arr

<ipython-input-90-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [92]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [93]:
np.max(arr)

10

In [94]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [95]:
np.log(arr)

<ipython-input-95-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])